### PR TITLE
Trac 1142

### PR DESCRIPTION
**Pull request by ghost**
** TRAC-1142**: https://jira.lib.utk.edu/browse/TRAC-1142

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, screenshots, etc.)

# What does this Pull Request do?

The pull request makes changes to a file that stores information about islandora trace rules.

# What's new?
The new rules will check for an object status indicator of incomplete before sending email. This change is needed so that emails are not sent for
every new object ingested during migration.

# How should this be tested?

Testing should be performed in two stages. The first stage will demonstrate how email is sent erroneously when ingesting collections via 
drush and the islandora_trace_

1.  Update the TRACE vm via your preferred method:
		a. git pull
		b. vagrant destroy /vagrant up
2.  Login as Admin and update the Rules. 
    a. open the file from the TRACE github project files/trace_dev.rules on the branch TRAC-1142 (easiest just to open https://github.com/utkdigitalinitiatives/TRACE/blob/TRAC-1142/files/trace_dev.rules )
    b. Goto admininal top nav bar's drop down window for Configuration > Workflow > Rules. 
    c. Delete the rule that is named 'rules_trace_publishing_workflow' or 'Trace Publishing Workflow' .
    d. Click on the button import rule. 
    e. For each entry in the github file trace_dev.rules, cut and paste a single rule, found between the dashed lines,  into the form. 
        e.1 Click 'Overwrite' and 
	e.2 click 'Import' button.

3. Set up AWS S3 authentication.  Migration will be run from the drush command line, but your environment is not set up to perform AWS S3 testing.
    a. First you will need to generate an application key for aunthetication if you do not have one already. (You don't)
     b. Get a user and password for Amazon from Don if you do not already have one. (Luckily you do, and I have the password that you need to reset)
    c. Sign in to the Console for AWS at https://039704682816.signin.aws.amazon.com/console
    d. IAM user name cdeane@utk.edu  Password: ??????
    e. Goto https://console.aws.amazon.com/iam/home#/home
    f. Click on the Dashboard link on the left sidebar.
    g. Click on 'Rotate your access keys' at the bottom of the page. Hit the button labeled 'Manage  #User Access Keys'
    h. On the Users Summary page, click on the Security credentials tab.
    i. You should see a button under the Access Keys heading named 'Create access key' . Hit it.
    j. Copy the credentials created into a text editor, you should have an access_key_id and a secret_access_key
    k. Format the text file to conform to :
```
    [default]
 	  aws_access_key_id = xxxxxxxxxxxxxxxx
 	  aws_secret_access_key = xxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx 
```
    l. open up a terminal in the TRACE vagrant project and ssh to vagrant:  vagrant ssh
    m. login as root (sudo -s)
    n. copy the contents of the text editor into a new file on TRACE vagrant : /etc/php5/.aws/credentials

4. As root, edit the following file: /var/www/drupal/sites/all/modules/islandora_xacml_editor/api/includes/parser.inc
   a. comment out the lines 46 - 51 that appear as
```
    if (!$dom->documentElement->hasAttribute('PolicyId') || $dom->documentElement->getAttribute("PolicyId") != 'islandora-xacml-editor-v1') {
      throw new XacmlException('XACML file was not written by XACML Editor.');
    }
```
5. As root, run the migration commands from drush.
   a. cd /var/www/drupal/sites/all/modules
   b.  drush ibdcsp --user=admin --input=/var/www/drupal/sites/all/modules/islandora_batch_digital_commons/config/trace_ingest_bepress.csv  --type=AWS
   c. you should see some output, as long as it is not an error. its good.
   d. drush ibdci --user=admin
   e. you will see a lot of output with some errors, if the errors only related to not being able to delete temporary files, then don't worry (a previous trigger deletes them before a later trigger tries again and fails because they are already deleted :) )
   f. exit from your root terminal.
   g. you should be able to view multiple emails by typing 'mail' at the terminal. 
   h.type 'd' at the terminal prompt until all emails are deleted. 
   i. 'q' quits mail.
6. Talk to Robert. He now has to modify     files/trace_dev.rules on the branch TRAC-1142  to change the rules to not email during a migration.
7. He's finally done? Good. Now, repeat Step 2 with the revisions that Robert has just committed. 
8. Oh good, now repeat 5, with the exception that at 5.g, you should have no email to review and stop the testing because it has passed.

# Additional Notes:
Any additional information that you think would be helpful when reviewing this PR. None

# Interested parties
Tag (@ mention) interested parties or, if unsure, @utkdigitalinitiatives/digital-initiatives-developers

### CODE REVIEW

**Comment by cdeaneGit** [comment]
I am resuming testing on this Pull Request 52

**Comment by DonRichards** [comment]
Step "5.e" did have errors as you said but I believe there was more that you suggested. Here's a screenshot. No emails generated. 
screen shot 2018-06-20 at 11 44 18 am

**Comment by ghost** [comment]
Don, I have the same errors now.

**Comment by cdeaneGit** [comment]
After multiple tests and revisions, today I tested per instructions and arrived at correct result.
I have uploaded the final rule set and today's successful test result to the Jira ticket TRAC-1142.
I approve this code.

**Review by cdeaneGit — APPROVED** [review]
I have tested this code multiple times.  Today I tested per instructions and the results were the correct results per Jira TRAC-1142.  Testing details are in the JIRA ticket TRAC-1142.  I approve this code for merge.

**Pull request merged**
