### PR TITLE
address TRAC-882: update the update_solr_config script (090) to refle…

### PR DESCRIPTION
**Pull request by CanOfBees**
…ct changes in the source configuration repository.

These changes update the `git clone` and `branch` behavior for the 090_update_solr custom shell script.

### How To Test ###
1. `vagrant destroy --force`
2. `git pull --all`
3. `git checkout -b remotes/origin/TRAC-882` (or your preferred method for checking TRAC-882 out for testing)
4. `vagrant up`
5. review the output of the startup at around the 090_... mark: are there any errors?
6. `vagrant ssh` and `cd /home/vagrant/utk-fedora-fedoragsearch-solr-config` and `git branch -a` should report `institutional_repository`

@robert-patrick-waltz @pc37utn @DonRichards @cdeaneGit

### CODE REVIEW

**Comment by DonRichards** [comment]
The branch is remotes/origin/HEAD -> origin/master

screen shot 2017-10-12 at 9 29 08 am

**Comment by CanOfBees** [comment]
@DonRichards hm, on my terminals, the '*' denotes the current branch. Is yours configured differently?

**Comment by markpbaggett** [comment]
@DonRichards, same here.  Also, seems to be that way for most people:

https://stackoverflow.com/questions/5059441/how-to-find-which-git-branch-i-am-on-when-my-disk-is-mounted-on-other-server

**Comment by DonRichards** [comment]
Thanks @CanOfBees & @markpbaggett but I found this issue. @CanOfBees I edited your instructions at the top
```terminal
$ git pull --all
$ git checkout -b remotes/origin/TRAC-882
$ vagrant up
```

**Comment by CanOfBees** [comment]
@DonRichards thanks for clarifying that!

**Comment by cdeaneGit** [comment]
My commits to this Pull Request have been added to the chain of requests. JIRA TRAC-875.
-------------------------------------------------------------------------------------------------
This is PART TWO of a TWO PULL request in support of JIRA TRAC-875.
(part 1 is in utk-fedora-fedoragsearch-solr-config(TRAC-875))
BOTH PULL REQUESTS SHOULD BE DONE BEFORE TESTING.

Code changes are in TRACE(TRAC-882)/scripts/custom_scripts/090_update_basic_solr_config.sh
The changes cause Trace to pull up the correct branch utk-fedora-fedoragsearch-solr-config(TRAC-875))

Testing instructions from https://groups.google.com/forum/#!msg/islandora/i6zC2wZNSMQ/o5IPOklALgAJ 

(written by Bridger)
1) navigate to your.server:8080/fedoragsearch/rest
2)authenticate
3) hit the updateIndex link
4) in the 4th box, updateIndex fromPid, enter your favorite PID and click `updateIndex fromPid`
5) check the PID's document in Solr

Please see this morning's comments about single_valued_hashsets in the Jira ticket.
@markpbaggett 
@CanOfBees

**Pull request closed without merging**
