### PR TITLE
Update Rules

### PR DESCRIPTION
**Pull request by DonRichards**
** JIRA Ticket**: https://jira.lib.utk.edu/browse/TRAC-1197

# What does this Pull Request do?
Only documents that a rule was updated and the value to use for email addresses of the student/user

# What's new?
@tennessee.edu email instead of the vols email

# How should this be tested?
Copy changes into production to verify a user with a vols email receives email after submitting.

# Additional Notes:
n/a

# Interested parties
@utkdigitalinitiatives/digital-initiatives-developers

### CODE REVIEW

**Comment by CanOfBees** [comment]
@DonRichards taking a look at this now.

**Review by CanOfBees — APPROVED** [review]
@DonRichards looks good!

**Comment by DonRichards** [comment]
Link to jire cloud for test https://jirautk.atlassian.net/browse/DIT-1143

**Comment by DonRichards** [comment]
DIT-1143 #time 2d 5h

**Comment by DonRichards** [comment]
testing

**Comment by DonRichards** [comment]
DIT-1143

**Comment by DonRichards** [comment]
DIT-1143 #time 2d 5h

**Pull request merged**
