### PR TITLE
Address TRAC-942.

### PR DESCRIPTION
**Pull request by markpbaggett**
** JIRA Ticket**: [TRAC-942](https://jira.lib.utk.edu/browse/TRAC-942)

# What does this Pull Request do?

This pull request gets a default form associated with binaries and compound objects in TRACE.

# What's new?

1. SQL Table dumps for 2 tables in Islandora are included.  These tables are used when the content model doesn't explicitly define a form (as in compound object).
2. Script 100 is changed so that Binary objects get the right form.
3. Script 900 has been modified so that Compound Objects get a form.

# How should this be tested?

1. vagrant destroy
2. vagrant up

# Additional Notes:

We have an issue with MySQL that I can't quite figure out.  For some reason, no matter where this is put in the codebase, it won't fire on Vagrant Up.  It does work when you execute the code after vagrant up.  It's baffling, and for the life of me, can't figure out why.  Since we're going to have to put this outside of deployment anyway, I decided to open the p.r.  If we want me to close, let's discuss.

**Note**: This is fixed. It couldn't find drush correctly.  It can now.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @utkdigitalinitiatives/digital-initiatives-developers

### CODE REVIEW

**Review by pc37utn — CHANGES_REQUESTED** [review]
if you are just adding the insert statement things, you don't need the drop table and create table lines, infact in the first if you got rid of everything but line 46 and 47 it may work.  For the other file it may be similar.

**Comment by pc37utn** [comment]
I'll check more soon, that was just the sql.

**Comment by markpbaggett** [comment]
@pc37utn, thanks for looking at this.  I brought this up later yesterday afternoon and have some other things I'm going to try this morning.  Would love any other feedback you think would be helpful.

**Comment by cdeaneGit** [comment]
I am testing first with no changes other than some echo commands on the scripts 900-.sh and 999-.sh to make the transcript more readable.

**Comment by cdeaneGit** [comment]
Following the steps: vagrant up and then execute 
/scripts/custom_scripts/900_load_solr_metadata_config_data.sh
The Trace site loads correctly.
1. Login as userA
2. Submit a work to Faculty and Graduate Student Research and Creative Work
3. Select file type: Islandora Compound Object Content Model
4. The form appears correctly.
5. Fill out and Submit the form.
6. Error Message:
Exception: Failed to create element. Value: &lt;title&gt;%value%&lt;/title&gt;.</br> Path: self::node()<br/>Context: parent</br> Error: Namespace Error in Create->doCreate() (line 200 of /var/www/drupal/sites/all/modules/islandora_xml_forms/api/Create.inc).

7.  The file associations needed to bring up this form properly.  The form itself has a problem, but that is not the concern of this issue.
PASS

Screen shots below:


I approve merging this code to the master branch.
submit_form_for_compobj_00
submit_form_for_compobj_01
submit_form_for_compobj_02

**Review by cdeaneGit — APPROVED** [review]
Following the steps in the test instruction, the file associations form correctly and the form loads.  There is a problem with the form itself that is outside the scope of this pull request.  
Detailed description of my testing in comments.
I approve merging of this code.

**Comment by CanOfBees** [comment]
@markpbaggett taking this out for a spin now

**Comment by markpbaggett** [comment]
@cdeaneGit, that's concerning.  I'm surprised we missed this during the p.r. that merged in that form.  Looking at this now.  No one merge anything.  In fact, I may go ahead and close this.

**Comment by pc37utn** [comment]
getting ready to test this,  I am looking at other systems to se why the tables that are being written to are blank.  Maybe they are supposed to be that way.  Just trying to catch up.

**Comment by pc37utn** [comment]
on digital, the same form_builder_form... table has entries for the large image and book cmodels, I still think this should be changed to a simple insert instead of rebuilding the entire table in case it could wipe out other inserts.

**Comment by markpbaggett** [comment]
@pc37utn, let me do that change. Let's hold off on further testing until that's done.

The issue with the form is here:
https://github.com/utkdigitalinitiatives/utk_isl_xml_forms/blob/master/xml_forms/UTK_ir_datasets.xml#L142

Going to try to get something in for that real quick.

**Comment by markpbaggett** [comment]
@pc37utn, changes should be addressed.  Also, vagrant up should work correctly now with that last commit.  Updating instructions.

**Review by pc37utn — APPROVED** [review]

**Review by CanOfBees — APPROVED** [review]
@markpbaggett looks great, thanks!

**Comment by pc37utn** [comment]
Merging now

**Pull request merged**
