### PR TITLE
adding in port forward for xdebug 9000

### PR DESCRIPTION
**Pull request by ghost**
The additional section does not execute on my machine, config.cm.provider is a method that is now operating off an empty array on my machine .

### CODE REVIEW

**Comment by markpbaggett** [comment]
So, I'm confused.  Line 16 starts a code block that says If this file exists on the Desktop then do something with a vm (customize a vm?)

Then on line 20 is another block that says unless this file on the desktop exists, forward port 9000?  

Sorry, I'm probably the worst person to review this, and I don't think I'd have as many problems if we had a .github/PULL_REQUEST_TEMPLATE.md, but I can't help but think that this code is to add an exception around one person.  Maybe this is way off, and if so I apologize.  

Do we have other things in the TRACE repository like this (exceptions around one person's environment)?  Did I totally misunderstand what's happening here.

**Comment by CanOfBees** [comment]
I think @markpbaggett has a good point -- this seems to be (or is) mostly a PR for individual changes. However, it's not clear to me how to accommodate this functionality without some change(s) to the Vagrantfile.

I looked for [examples of a multiple vagrantfile setup](https://github.com/erran-r7/multiple_vagrantfiles), but I'm not sure if this will help alleviate issues. Are there other ways to keep this sort of local functionality, but not fill up the main Vagrantfile?

**Comment by ghost** [comment]
I am the only one who may benefit from most from this request since the logic is establishing a local NAT connection between TRACE and a development VM.  In particular lines 15 - 22 are for setting up a NAT network between two virtual machines.  
The lines 28 - 30 are for creating a 9000 port connection on a localhost machine.  
We can reject this request and only add in line 29 to the appropriate place in the Vagrantfile.

**Comment by markpbaggett** [comment]
So, I know @robert-patrick-waltz has suggested closing this p.r., but before we do, I just want to say that I think we should consider what to do about this sort of thing. 

- Are there other things like this that people would want to do for their own development environments?
- Should we allow this sort of thing or would this potentially cause us issues in testing (people running different boxes, machines, etc.)
- If we do allow, what would be the scope of acceptable practice?
- If we do allow, how can we accommodate with out tracking everyone's local stuff?

**Comment by CanOfBees** [comment]
Closing this.

**Pull request closed without merging**
