### PR TITLE
Sprint #11

### PR DESCRIPTION
**Pull request by DonRichards**
Completing Sprint #11 TRAC-818

### CODE REVIEW

**Review by pc37utn — COMMENTED** [review]
many changes, not sure about the travis failures...
one thing we might want to look at -- Cricket's last change went into the islandora_solr_metadata.tpl.php and it is being kept in the files directory and then copied to teh templates dir.  If we ever update the theme, her changes will get wiped out, might want to copy it to the UTKdrupal repo.

**Comment by markpbaggett** [comment]
@pc37utn, good looking out there.  Yes, if it's a tpl change, it needs to be in UTK Drupal.  I'll bring up at standup.

**Comment by DonRichards** [comment]
During standup it was suggested to skip the separation and fix later.

**Comment by CanOfBees** [comment]
Based on discussion at this morning's standup: we'll merge and then split code out appropriately.

Thanks @DonRichards @cdeaneGit @robert-patrick-waltz and @pc37utn for their feedback.

**Review by CanOfBees — APPROVED** [review]
Updated some of the modified shellscripts to pass shellcheck linting.

**Pull request merged**
