### PR TITLE
install JAIL library, add variable for jail

### PR DESCRIPTION
**Pull request by pc37utn**
** JIRA Ticket**: (link)

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, screenshots, etc.)

# What does this Pull Request do?
 install the JAIL library for options in the compound solution pack
sets teh variable to enable the JAIL block for the compound object display

# How should this be tested?
 -  Run a clean vagrant up, check to see if JAIL library is installed in the libraries directory,
 - check the admin page for the compound object to see if it has the option set for the jail block.
 - check the struture to see if a jail block is available

# Interested parties
Tag @utkdigitalinitiatives/digital-initiatives-developers

### CODE REVIEW

**Comment by pc37utn** [comment]
re-assigned this to Mark and removed reviewer

**Comment by pc37utn** [comment]
accidentally clicked on hte link to "assign this to yourself".  fixed that.

**Comment by markpbaggett** [comment]
@pc37utn reviewing now.  Sorry for letting this hang out for so long.

**Comment by markpbaggett** [comment]
@pc37utn JAIL is displaying, but it doesn't look like thumbnails are loading properly for children to the DOM.  Instead, it's just showing a loader.png.  Is this what you're getting too?  Want to be sure we're seeing same thing before merge.

**Comment by markpbaggett** [comment]
Actually, I think this is a permissions thing based on how I did my test.  Let me do this a different way.

**Comment by pc37utn** [comment]
according to what Dan said yesterday all of vagrant and dlhost is not working

**Comment by pc37utn** [comment]
wait that was an issue with search and text results, nevermind

**Review by markpbaggett — APPROVED** [review]
@pc37utn this looks good.  Merging.

**Pull request merged**
